name: srtool-build
description: Build a substrate-based runtime with srtool
author: Martin Pugh (pugh@s3kr.it)
inputs:
  runtime:
    description: "Name of the runtime to build"
    default: "polkadot-runtime"
    required: true
  profile:
    description: "Rust build profile to build the runtime with (e.g., release, debug...)"
    default: "release"
    required: true
outputs:
  prop:
    description: Proposal hash of the generated runtime
  sha256:
    description: SHA256SUM of the generated runtime
runs:
  using: docker
  image: 'Dockerfile'
